language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build grammatek-tts.gemspec
  - gem install ./grammatek-tts-0.5.gem
