# -*- encoding: utf-8 -*-

=begin
#TTS API

#This API gives access to Grammatek ehf advanced text to speech services. It provides endpoints to query all available voices and synthesize speech from given text for a particular voice. You can synthesize speech in several audio formats and different sample rates. Please authenticate with your client credentials via the /auth/v1 endpoint to receive a temporary access token for all API endpoints. This token is valid only for a certain time and you need to re-authenticate after it has expired. Please contact Grammatek via info@grammatek.com to receive your individual client credentials. 

The version of the OpenAPI document: v1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "grammatek-tts/version"

Gem::Specification.new do |s|
  s.name        = "grammatek-tts"
  s.version     = GTTS::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Daniel Schnell"]
  s.email       = ["dschnell@grammatek.com"]
  s.homepage    = "https://github.com/grammatek/tts-ruby-gem"
  s.summary     = "A Ruby wrapper for the Grammatek ehf TTS REST API"
  s.description = "This is the official Ruby Gem for Grammatek TTS API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.6"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
