# -*- encoding: utf-8 -*-

=begin
#TTS API

#This API gives access to Grammatek ehf text to speech services.

The version of the OpenAPI document: v0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "grammatek-tts/version"

Gem::Specification.new do |s|
  s.name        = "grammatek-tts"
  s.version     = Grammatek::TTS::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Daniel Schnell"]
  s.email       = ["dschnell@grammatek.com"]
  s.homepage    = "https://gitlab.com/grammatek/tts-ruby-gem"
  s.summary     = "A Ruby wrapper for the Grammatek ehf REST API"
  s.description = "This is the official Ruby Gem for Grammatek TTS API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
