=begin
#TTS API

#This API gives access to Grammatek ehf text to speech services.

The version of the OpenAPI document: v0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Grammatek::TTS::SpeechApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpeechApi' do
  before do
    # run before each test
    @api_instance = Grammatek::TTS::SpeechApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpeechApi' do
    it 'should create an instance of SpeechApi' do
      expect(@api_instance).to be_instance_of(Grammatek::TTS::SpeechApi)
    end
  end

  # unit tests for speech_post
  # TTS - Synthesize speech from text
  # @param [Hash] opts the optional parameters
  # @option opts [SynthesizeSpeechRequest] :synthesize_speech_request 
  # @return [Object]
  describe 'speech_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for voices_get
  # Describe/query available voices
  # @param [Hash] opts the optional parameters
  # @option opts [String] :engine Specify which engine to use
  # @option opts [String] :language_code The language identification tag (ISO 639 code for the language name-ISO 3166 country code) for filtering the list of voices returned. If you don&#39;t specify this optional parameter, all available voices are returned.  example: is-IS
  # @return [Array<Voice>]
  describe 'voices_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
