=begin
#TTS API

#This API gives access to Grammatek ehf text to speech services.

The version of the OpenAPI document: v0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Grammatek::TTS::Error
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Grammatek::TTS::Error do
  let(:instance) { Grammatek::TTS::Error.new }

  describe 'test an instance of Error' do
    it 'should create an instance of Error' do
      expect(instance).to be_instance_of(Grammatek::TTS::Error)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
