=begin
#TTS API

#This API gives access to Grammatek ehf text to speech services.

The version of the OpenAPI document: v0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'grammatek-tts/api_client'
require 'grammatek-tts/api_error'
require 'grammatek-tts/version'
require 'grammatek-tts/configuration'

# Models
require 'grammatek-tts/models/error'
require 'grammatek-tts/models/synthesize_speech_request'
require 'grammatek-tts/models/voice'

# APIs
require 'grammatek-tts/api/speech_api'

module Grammatek::TTS
  class << self
    # Customize default settings for the SDK using block.
    #   Grammatek::TTS.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
