=begin
#TTS API

#This API gives access to Grammatek ehf advanced text to speech services. It provides endpoints to query all available voices and synthesize speech from given text for a particular voice. You can synthesize speech in several audio formats and different sample rates. Please authenticate with your client credentials via the /auth/v1 endpoint to receive a temporary access token for all API endpoints. This token is valid only for a certain time and you need to re-authenticate after it has expired. Please contact Grammatek via info@grammatek.com to receive your individual client credentials. 

The version of the OpenAPI document: v1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

# Common files
require 'grammatek-tts/api_client'
require 'grammatek-tts/api_error'
require 'grammatek-tts/version'
require 'grammatek-tts/configuration'

# Models
require 'grammatek-tts/models/auth_request'
require 'grammatek-tts/models/auth_response'
require 'grammatek-tts/models/error'
require 'grammatek-tts/models/synthesize_speech_request'
require 'grammatek-tts/models/token_info_response'
require 'grammatek-tts/models/voice'

# APIs
require 'grammatek-tts/api/auth_api'
require 'grammatek-tts/api/speech_api'

module GTTS
  class << self
    # Customize default settings for the SDK using block.
    #   GTTS.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
