=begin
#TTS API

#This API gives access to Grammatek ehf text to speech services.

The version of the OpenAPI document: v0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'

describe Grammatek::TTS::Configuration do
  let(:config) { Grammatek::TTS::Configuration.default }

  before(:each) do
    # uncomment below to setup host and base_path
    # require 'URI'
    # uri = URI.parse("https://api.grammatek.com/tts/v0")
    # Grammatek::TTS.configure do |c|
    #   c.host = uri.host
    #   c.base_path = uri.path
    # end
  end

  describe '#base_url' do
    it 'should have the default value' do
      # uncomment below to test default value of the base path
      # expect(config.base_url).to eq("https://api.grammatek.com/tts/v0")
    end

    it 'should remove trailing slashes' do
      [nil, '', '/', '//'].each do |base_path|
        config.base_path = base_path
        # uncomment below to test trailing slashes
        # expect(config.base_url).to eq("https://api.grammatek.com/tts/v0")
      end
    end
  end
end
